Name: ecommerceconfig
---
EcommerceConfig:
  folder_and_file_locations:
    - "mysite/_config/ecommerce.yml"

SSViewer:
  theme: main


WebpackPageControllerExtension:
  webpack_enabled_themes:
    - sswebpack

Email:
  admin_email: ecom-sales@sunnysideup.co.nz
