---
Name: ecommerceconfig
---
Sunnysideup\Ecommerce\Config\EcommerceConfig:
  folder_and_file_locations:
    - "app/_config/ecommerce.yml"

Sunnysideup\WebpackRequirementsBackend\Api\Configuration:
  webpack_enabled_themes:
    - ecommerce-demo-theme
    - ecommerce-demo-theme

SilverStripe\Control\Email\Email:
  admin_email: ssuerrors@gmail.com

Sunnysideup\GoogleAnalyticsBasics\GoogleAnalyticsSTE:
  main_code: 'UA-26108878-1' #e.g. UA-xxxx-y

SilverStripe\Core\Manifest\ModuleManifest:
  project: app
