Name: ecommerceconfig
---
EcommerceConfig:
  folder_and_file_locations:
    - "app/_config/ecommerce.yml"

SSViewer:
  theme: main


WebpackPageControllerExtension:
  webpack_enabled_themes:
    - sswebpack

Email:
  admin_email: ssuerrors@gmail.com

GoogleAnalyticsSTE:
  main_code: 'UA-26108878-1' #e.g. UA-xxxx-y
