mappings:
  CompleteSetupRecord: Sunnysideup\EcommerceTest\Model\CompleteSetupRecord
  CleanEcommerceTables: Sunnysideup\EcommerceTest\Tasks\SetUpEcommerceRecordsStep1
  DefaultRecordsForEcommerce: Sunnysideup\EcommerceTest\Tasks\SetUpEcommerceRecordsStep2
